CREATE TABLE w_wopeople (
    spec_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    woIdTX VARCHAR(20) NOT NULL,
    woNameTX VARCHAR(330) NOT NULL,
    woUserNameTX VARCHAR(100) NOT NULL,
    woPositionNameTX VARCHAR(150),
    woFirstNameTX VARCHAR(150),
    woFamilyNameTX VARCHAR(150),
    woSurnameTX VARCHAR(150),
    woMenuLI VARCHAR(1000),
    wUserPassTX VARCHAR(700),
    woHomePageLI VARCHAR(1000),
    woOrgNameTX VARCHAR(1000),
    woEmailTX VARCHAR(50),
    woRecordStateSY VARCHAR(100) NOT NULL,
    woPreviousStateSY VARCHAR(100) NOT NULL,
    woStatusCL VARCHAR(150),
    woPreviousStatusCL VARCHAR(150),
    woFormNameSY VARCHAR(150) NOT NULL,
    primary key (spec_id) );
INSERT INTO s_state(wo_name, wo_state)
     VALUES ('woPeople', 'null'),
            ('woPeople', 'woDraft'),
            ('woPeople', 'woActive'),
            ('woPeople', 'woRetired');
INSERT INTO s_state_transit(
    wo_name, current_state, next_state, action_name, action_label, close_window, read_only, secondary_action)
VALUES ('woPeople', 'null', 'woDraft', 'woCreate', 'Create', FALSE, FALSE, FALSE),
       ('woPeople', 'woDraft', 'woActive','woActivate', 'Activate', FALSE, FALSE, TRUE),
       ('woPeople', 'woDraft', 'woRetired', 'woRetire', 'Retire', FALSE, FALSE, FALSE),
       ('woPeople', 'woActive', 'woRetired', 'woRetire', 'Retire', FALSE, FALSE, FALSE),
       ('woPeople', 'woActive', 'woActive', 'woActivate', 'Retire', FALSE, FALSE, FALSE),
       ('woPeople', 'woRetired', 'null', 'woDelete', 'Delete', FALSE, FALSE, FALSE);
INSERT INTO s_statetransit_subaction(
    action_name, id_state_transit, process_name)
SELECT t.action_name, t.id_state_transit, 'woPeople - Synchronous - when Create'
  FROM s_state_transit t
 WHERE t.wo_name = 'woPeople' AND t.current_state = 'null' AND t.next_state = 'woDraft' AND t.action_name = 'woCreate';
INSERT INTO s_statetransit_subact_inclusion(
    action_name, inclusion, exclusion, id_state_transit, id_statetransit_subact)
SELECT 'transitA', TRUE, FALSE, t.id_state_transit, s.id_statetransit_subact
  FROM s_state_transit t JOIN s_statetransit_subaction s ON t.id_state_transit = s.id_state_transit
 WHERE t.wo_name = 'woPeople' AND t.current_state = 'null' AND t.next_state = 'woDraft' AND t.action_name = 'woCreate';
INSERT INTO s_statetransit_subact_inclusion(
    action_name, inclusion, exclusion, id_state_transit, id_statetransit_subact)
SELECT 'transitB', FALSE, TRUE, t.id_state_transit, s.id_statetransit_subact
  FROM s_state_transit t JOIN s_statetransit_subaction s ON t.id_state_transit = s.id_state_transit
 WHERE t.wo_name = 'woPeople' AND t.current_state = 'null' AND t.next_state = 'woDraft' AND t.action_name = 'woCreate';
INSERT INTO s_statetransit_subact_attribute(
    field_name, const_value, id_state_transit, id_statetransit_subact)
SELECT 'woStateSY', 'Draft', t.id_state_transit, s.id_statetransit_subact
  FROM s_state_transit t JOIN s_statetransit_subaction s ON t.id_state_transit = s.id_state_transit
 WHERE t.wo_name = 'woPeople' AND t.current_state = 'null' AND t.next_state = 'woDraft' AND t.action_name = 'woCreate';
INSERT INTO s_statetransit_subact_attribute(
    field_name, const_value, id_state_transit, id_statetransit_subact)
SELECT 'woPreviousStateSY', 'null', t.id_state_transit, s.id_statetransit_subact
  FROM s_state_transit t JOIN s_statetransit_subaction s ON t.id_state_transit = s.id_state_transit
 WHERE t.wo_name = 'woPeople' AND t.current_state = 'null' AND t.next_state = 'woDraft' AND t.action_name = 'woCreate';
INSERT INTO w_wopeople (
       woIdTX, woNameTX, woUserNameTX, woHomePageLI, woRecordStateSY, woPreviousStateSY, woFormNameSY)
VALUES ('1', 'leaseAdmin', 'leaseAdmin', 'wo-leaseAdmin - portal', 'woActive', 'null', 'WoEmployee');
