CREATE TABLE s_nav_item (
    nav_item_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nav_item_name VARCHAR(500) NOT NULL,
    nav_item_label VARCHAR(500) NOT NULL,
    nav_item_type VARCHAR(50) DEFAULT 'DEFAULT',
    --nav_item_type VARCHAR(50) NOT NULL,
    nav_item_wo_id BIGINT,
    nav_item_wo_name VARCHAR(330),
    nav_item_wo_type VARCHAR(50) DEFAULT 'WO_PORTAL_SETTINGS',
    nav_item_wo_form VARCHAR(150),
    nav_item_wo_query VARCHAR(150),
    --ui_target_id BIGINT,
    image_path VARCHAR(500),
    dynalabel_flag TINYINT,
    dynalabel_prefix VARCHAR(500),
    dynalabel_suffix VARCHAR(500),
    dynalabel_rep_template_id BIGINT,
    site_map_only TINYINT,
    help_text VARCHAR(500),
--object_label_id BIGINT NOT NULL DEFAULT -1,
--sys_comment VARCHAR(500),
    primary key (nav_item_id) );
CREATE TABLE s_nav_collection (
    nav_collection_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nav_collection_name VARCHAR(500) NOT NULL,
    nav_collection_label VARCHAR(500) NOT NULL,
    nav_collection_type VARCHAR(50) DEFAULT 'DEFAULT',
    description VARCHAR(500),
    help_text VARCHAR(500),
--object_label_id BIGINT NOT NULL DEFAULT -1,
--sys_comment VARCHAR(500),
    primary key (nav_collection_id) );
CREATE TABLE s_nav_collection_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nav_collection_id INTEGER NOT NULL,
    parent_nav_item_id INTEGER NOT NULL,
    child_nav_item_id INTEGER NOT NULL,
    child_nav_item_seq INTEGER NOT NULL,
    primary key (id) );
CREATE TABLE s_portal_section (
    portal_section_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    portal_section_name VARCHAR(500) NOT NULL,
    portal_section_label VARCHAR(500) NOT NULL,
    ql_collection INTEGER,--nav_collection_id
    ql_type VARCHAR(50) DEFAULT 'DEFAULT',
    --section_data_id INTEGER,
    section_type VARCHAR(50) DEFAULT 'DEFAULT',
    url_name VARCHAR(400),
    header_name VARCHAR(400),
    hdr_font VARCHAR(50) DEFAULT 'trebuchet',
    hdr_size TINYINT DEFAULT 10,
    hdr_weight VARCHAR(50) DEFAULT 'bold',
    hdr_position TINYINT NOT NULL DEFAULT 2,
    hdr_fg_color VARCHAR(50) DEFAULT 'white',
    bg_color VARCHAR(50) DEFAULT 'white',
    bg_image VARCHAR(500),
    tooltip VARCHAR(500),
    --related_link VARCHAR(400),
    pre_workprocess VARCHAR(500),
    show_query_actions TINYINT DEFAULT 0,
    max_to_show TINYINT DEFAULT 10,
    description VARCHAR(500),
    hide_metric_filter TINYINT DEFAULT 1,
    auto_resize_flag TINYINT DEFAULT 0,
    show_header_flag TINYINT DEFAULT 1,
    auto_refresh_flag TINYINT DEFAULT 0,
    refresh_time TINYINT DEFAULT 10,
    scope_flag TINYINT DEFAULT 0,
    --owner_id BIGINT DEFAULT 0,
    --object_label_id BIGINT NOT NULL DEFAULT -1,
    --sys_comment VARCHAR(500),
    primary key (portal_section_id) );
CREATE TABLE s_portal_hdr (
    portal_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    portal_name VARCHAR(500) NOT NULL,
    portal_label VARCHAR(500) NOT NULL,
    description VARCHAR(500),
    layout_type VARCHAR(50) NOT NULL,
    --object_label_id BIGINT NOT NULL DEFAULT -1,
    --sys_comment VARCHAR(500),
    primary key (portal_id) );
CREATE TABLE s_portal_layout (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    portal_id INTEGER,
    portal_section_id INTEGER,
    column_num TINYINT,
    column_seq TINYINT,
    default_collapsed TINYINT NOT NULL DEFAULT 1,
    primary key (id) );
INSERT INTO s_nav_item(nav_item_name, nav_item_label, nav_item_wo_id)
     VALUES ('wo-lease - Space nav item', 'Работа с объектами', 1),
            ('wo-lease - Contract nav item', 'Работа с договорами', 2);
INSERT INTO s_nav_collection(nav_collection_name, nav_collection_label)
     VALUES ('wo-lease - Space collection', 'Объекты'),
            ('wo-lease - Contract collection', 'Договоры');
INSERT INTO s_portal_hdr(portal_name, portal_label, layout_type)
     VALUES ('wo-lease - portal', 'Аренда недвижимости', 0);
INSERT INTO s_portal_section(portal_section_name, portal_section_label, ql_collection)
     VALUES ('wo-lease - Space section', 'Объекты', 1),
            ('wo-lease - Contract section', 'Договоры', 2);
INSERT INTO s_portal_layout(portal_id, portal_section_id, column_num, column_seq)
     VALUES (1, 1, 1, 0),
            (1, 2, 1, 1)
