create table w_classification
(
    spec_id            bigint generated by default as identity,
    woCodeTX           varchar(50)   not null,
    woDescriptionTX    varchar(500),
    woFormNameSY       varchar(150)  not null,
    woIdTX             varchar(20)   not null,
    woNameTX           varchar(330)  not null,
    woPathTX           varchar(1000) not null,
    woPreviousStateSY  varchar(100)  not null,
    woPreviousStatusCL varchar(150),
    woRecordStateSY    varchar(100)  not null,
    woStatusCL         varchar(150),
    woUserCommentTX    varchar(50),
    primary key (spec_id)
);
create table w_contract
(
    spec_id            bigint generated by default as identity,
    woBeginDA          date,
    woCommentTX        varchar(400),
    woDescriptionTX    varchar(1000),
    woEndDA            date,
    woFormNameSY       varchar(150) not null,
    woIdTX             varchar(20)  not null,
    woNameTX           varchar(330) not null,
    woPreviousStateSY  varchar(100) not null,
    woPreviousStatusCL varchar(150),
    woRecordStateSY    varchar(100) not null,
    woStatusCL         varchar(150),
    primary key (spec_id)
);
create table w_contract_locations
(
    spec_id            bigint generated by default as identity,
    woAddressTX        varchar(1000) not null,
    woBeginDA          date,
    woCommentTX        varchar(400),
    woDescriptionTX    varchar(1000),
    woEndDA            date,
    woFormNameSY       varchar(150)  not null,
    woIdTX             varchar(20)   not null,
    woNameTX           varchar(330)  not null,
    woPreviousStateSY  varchar(100)  not null,
    woPreviousStatusCL varchar(150),
    woRecordStateSY    varchar(100)  not null,
    woStatusCL         varchar(150),
    primary key (spec_id)
);
create table w_contract_tenant
(
    spec_id            bigint generated by default as identity,
    woBeginDA          date,
    woCommentTX        varchar(400),
    woDescriptionTX    varchar(1000),
    woEndDA            date,
    woFormNameSY       varchar(150) not null,
    woIdTX             varchar(20)  not null,
    woInnTX            varchar(13),
    woNameTX           varchar(330) not null,
    woPreviousStateSY  varchar(100) not null,
    woPreviousStatusCL varchar(150),
    woRecordStateSY    varchar(100) not null,
    woShortNameTX      varchar(50),
    woStatusCL         varchar(150),
    primary key (spec_id)
);
create table w_organization
(
    spec_id            bigint generated by default as identity,
    woCommentTX        varchar(400),
    woDescriptionTX    varchar(1000),
    woFormNameSY       varchar(150) not null,
    woFullNameTX       varchar(150),
    woIdTX             varchar(20)  not null,
    woInnTX            varchar(11),
    woKppTX            varchar(10),
    woNameTX           varchar(330) not null,
    woOgrnTX           varchar(14),
    woOkpoTX           varchar(9),
    woPreviousStateSY  varchar(100) not null,
    woPreviousStatusCL varchar(150),
    woRecordStateSY    varchar(100) not null,
    woShortNameTX      varchar(50),
    woStatusCL         varchar(150),
    primary key (spec_id)
);
create table w_portal_settings
(
    spec_id            bigint generated by default as identity,
    woFormNameSY       varchar(150) not null,
    woIdTX             varchar(20)  not null,
    woNameTX           varchar(330) not null,
    woPreviousStateSY  varchar(100) not null,
    woPreviousStatusCL varchar(150),
    woRecordStateSY    varchar(100) not null,
    woStatusCL         varchar(150),
    primary key (spec_id)
);
create table w_wospace
(
    spec_id            bigint generated by default as identity,
    woAddressTX        varchar(1000) not null,
    woCommentTX        varchar(400),
    woDescriptionTX    varchar(1000),
    woFormNameSY       varchar(150)  not null,
    woIdTX             varchar(20)   not null,
    woKnTX             varchar(26),
    woNameTX           varchar(330)  not null,
    woPreviousStateSY  varchar(100)  not null,
    woPreviousStatusCL varchar(150),
    woRecordStateSY    varchar(100)  not null,
    woStatusCL         varchar(150),
    primary key (spec_id)
)
